#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "commafeed"
name = "CommaFeed"
description.en = "Personal RSS reader"
description.fr = "Lecteur RSS personnel"

version = "7.2.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "Apache-2.0"
website = "https://www.commafeed.com/"
demo = "https://www.commafeed.com/#/app/category/all"
code = "https://github.com/Athou/commafeed"
fund = "https://www.paypal.com/donate/?business=9CNQHMJG2ZJVY&no_recurring=0&item_name=CommaFeed&currency_code=EUR"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = false

ldap = false
sso = false

disk = "50M"
ram.build = "100M"
ram.runtime = "100M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    rename = "commafeed"
    in_subdir = false
    extract = false
    amd64.url = "https://github.com/Athou/commafeed/releases/download/7.2.0/commafeed-7.2.0-h2-linux-x86_64-runner"
    amd64.sha256 = "e4e9f05fcacb74cfe69c9d5c05bae686ddf2c8c1da3899b71984e2c97b429172"
    arm64.url = "https://github.com/Athou/commafeed/releases/download/7.2.0/commafeed-7.2.0-h2-linux-aarch_64-runner"
    arm64.sha256 = "47c176e3908f872037edb65fd68b3a1c268b434f58a48c2a7615315430c0db19"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "commafeed-\\d+\\.\\d+\\.\\d+-h2-linux-x86_64-runner"
    autoupdate.asset.arm64 = "commafeed-\\d+\\.\\d+\\.\\d+-h2-linux-aarch_64-runner"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    main.auth_header = false

    [resources.ports]
